const fs = require('fs');
const lines = [
  "import React from 'react';",
  "import Link from 'next/link';",
  "",
  "export default function HomePage() {",
  "  return (",
  "    <div className='min-h-screen bg-gray-50 flex flex-col'>",
  "      <header className='bg-white shadow-sm'>",
  "        <div className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center'>",
  "          <div className='font-bold text-xl text-blue-900'>Vorynex Automation</div>",
  "          <div className='space-x-4'>",
  "            <Link href='/login' className='text-gray-600 hover:text-gray-900'>Sign In</Link>",
  "            <Link href='/register' className='bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700'>Get Started</Link>",
  "          </div>",
  "        </div>",
  "      </header>",
  "",
  "      <main className='flex-grow flex flex-col items-center justify-center text-center px-4'>",
  "        <h1 className='text-5xl font-extrabold text-gray-900 mb-6'>",
  "          Intelligent Manufacturing Copilot",
  "        </h1>",
  "        <p className='text-xl text-gray-600 max-w-2xl mb-10'>",
  "          Streamline your supply chain, automate invoice approvals, and manage your inventory with our enterprise-grade AI Operations platform.",
  "        </p>",
  "        <div className='flex space-x-4'>",
  "          <Link href='/register' className='bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-semibold hover:bg-blue-700'>",
  "            Start Free Trial",
  "          </Link>",
  "          <Link href='/login' className='bg-white text-blue-600 px-8 py-3 rounded-lg text-lg font-semibold border border-blue-200 hover:bg-gray-50'>",
  "            Enter Workspace",
  "          </Link>",
  "        </div>",
  "      </main>",
  "",
  "      <footer className='bg-gray-900 text-white py-8 text-center'>",
  "        <p>2026 Vorynex Technologies. Stage 42 Certified Release.</p>",
  "      </footer>",
  "    </div>",
  "  );",
  "}"
];
fs.writeFileSync('src/app/page.tsx', lines.join('\n'), 'utf8');
